version: "3.8"

services:
  mongo:
    image: mongo
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: $ADMIN_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $ADMIN_PASSWORD
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-volume:/data/db
  mongo-express:
    image: mongo-express
    restart: no
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: $MONGODB_URL

volumes:
  mongo-volume:
