version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: no
    ports:
      - "27017:27017"
    volumes:
      - ./db/start.sh:/usr/local/bin/start.sh:ro
      - ./db/initialize_db.sh:/usr/local/bin/initialize_db.sh:ro
      - ./db/replica-init.js:/after-run-scripts/replica-init.js:ro
      - ./db/mongo-init.js:/after-run-scripts/mongo-init.js:ro
      - mongo-volume:/data/db
    command: [ "--replSet", "mainReplicaSet" ]
    entrypoint: [ "start.sh" ]
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: no
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017

volumes:
  mongo-volume:
