applicationType: default
defaultPackage: com.example.infrastructure
testFramework: junit
sourceLanguage: java
buildTool: maven
features: [app-name, data, data-mongodb-reactive, http-client-test, java, java-application, junit, logback, maven, maven-enforcer-plugin, micronaut-aot, micronaut-http-validation, mongo-reactive, netty-server, properties, readme, rxjava3, serialization-jackson, shade, static-resources, test-resources]
